language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t caocmai/react-themoviedb -f Dockerfile.dev .

script:
  - docker run -e CI=true caocmai/react-themoviedb npm run test

after_success:
  - docker build -t caocmai/react-themoviedb .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push caocmai/react-themoviedb